---
- hosts: jenkins
  
  tasks:
 
  - name: start a jenkins container
    shell: docker run -d -p 8080:8080 -p 50000:50000 -v /var/run/docker.sock:/var/run/docker.sock --name jenkins jenkins/jenkins:lts

  - name: update apt-cache
    shell: docker exec -u root jenkins apt-get -y update

  - name: install docker pre-reqs inside jenkins container
    shell: docker exec -u root jenkins apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common vim python-dev

  - name: install docker apt gpg key
    shell: docker exec -u root jenkins curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg -o /tmp/dkey

  - name: add gpg key
    shell: docker exec -u root jenkins apt-key add /tmp/dkey

  - name: add docker apt repo in jenkins container
    shell: docker exec -u root jenkins add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) stable"

  - name: update apt cache in jenkins container
    shell: docker exec -u root jenkins apt-get update -y
  
  - name: install docker-ce
    shell: docker exec -u root jenkins apt-get install -y docker-ce

  - name: add user jenkins to docker group
    shell: docker exec -u root jenkins usermod -aG docker jenkins
