---
- hosts: docker

  tasks:

  - name: install pre-requisites
    apt: 
      name: "{{ packages }}"
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: download docker gpg
    apt_key: 
      id: 0EBFCD88
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker apt repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
      state: present

  - name: install docker-ce
    apt:
      name: docker-ce
      update_cache: yes
      state: present

  - name: start docker service
    systemd:
      name: docker
      enabled: yes
      state: started

  - name: add devops user to docker group
    user:
      name: devops
      groups: docker
      append: yes

#  - name: create /etc/docker/ssl

#  - name: create ~/.docker

#  - name: generate ca-key

#  - name: generate ca-key certificates

#  - name: copy ca-key certificates to /etc/docker/ssl

#  - name: configure client side ssl

#  - name: configure server side ssl

  
